name: mental_health_app
description: A new Flutter project.
#publish_to: 'none' # Remove this line if publishing to pub.dev

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  flutter_hooks: ^0.21.2
  intl: ^0.20.2
  http: ^1.2.1
  fl_chart: ^1.0.0
  flutter_local_notifications: ^14.1.5
  timezone: ^0.9.4
  permission_handler: ^12.0.0+1
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.1
  google_sign_in: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
    - family: NotoEmoji
      fonts:
        - asset: assets/fonts/NotoEmoji-Regular.ttf
  assets:
    - assets/images/profile_placeholder.png
