// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLWOpIt4zAMKL-16G-Ha9xOBeWVFGJw0U',
    appId: '1:922776185803:web:4eb7f3be15a5e2efd2644e',
    messagingSenderId: '922776185803',
    projectId: 'mental-health-app-9d009',
    authDomain: 'mental-health-app-9d009.firebaseapp.com',
    storageBucket: 'mental-health-app-9d009.firebasestorage.app',
    measurementId: 'G-JJPZJPZSD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB87JH3lBU5jxLn0Cq7fzA_zPdcSbyR76o',
    appId: '1:922776185803:android:d82b7d50be1f18ccd2644e',
    messagingSenderId: '922776185803',
    projectId: 'mental-health-app-9d009',
    storageBucket: 'mental-health-app-9d009.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE87QnuVjHPCCkG0XBrgDnV__TVcZrYL0',
    appId: '1:922776185803:ios:38f9e5d57eb12af6d2644e',
    messagingSenderId: '922776185803',
    projectId: 'mental-health-app-9d009',
    storageBucket: 'mental-health-app-9d009.firebasestorage.app',
    iosBundleId: 'com.example.mentalHealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE87QnuVjHPCCkG0XBrgDnV__TVcZrYL0',
    appId: '1:922776185803:ios:38f9e5d57eb12af6d2644e',
    messagingSenderId: '922776185803',
    projectId: 'mental-health-app-9d009',
    storageBucket: 'mental-health-app-9d009.firebasestorage.app',
    iosBundleId: 'com.example.mentalHealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLWOpIt4zAMKL-16G-Ha9xOBeWVFGJw0U',
    appId: '1:922776185803:web:b6771a3731b292d4d2644e',
    messagingSenderId: '922776185803',
    projectId: 'mental-health-app-9d009',
    authDomain: 'mental-health-app-9d009.firebaseapp.com',
    storageBucket: 'mental-health-app-9d009.firebasestorage.app',
    measurementId: 'G-YZ6MPDCS7K',
  );
}
